# Generated by Django 6.0 on 2026-01-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_updated_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Business', 'Business'), ('Technology', 'Technology'), ('Photography', 'Photography'), ('Sustainability', 'Sustainability'), ('Lifestyle', 'Lifestyle'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Landscape', 'Landscape'), ('City', 'City'), ('Adventure', 'Adventure'), ('Beach', 'Beach'), ('Sky', 'Sky'), ('Water', 'Water'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
