# Generated by Django 6.0.3 on 2026-04-09 20:23

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_blogblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogblock',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='products/'),
        ),
    ]
